apiVersion: v1
kind: Service
metadata:
  name: mavenapp-service
spec:
  selector:
    app: mavenapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31110
